url: https://boluihv.github.io
baseurl: '/agency-jekyll-theme/'

# Site settings
title: İhlas Vakfı Özel Bolu Yüksek Öğrenim Erkek Öğrenci Yurdu
email: bilgi@boluyurt.com
description: "İhlas Vakfı Bolu Özel Erkek Öğrenci Yurdu"

# API settings
google_api_key: AIzaSyCZHCDJgfaIVioMbqvAvKrUjTnBJBW0H2Q

# Team names, titles and social links
people:
- name: Cihangir Abdullah Adak
  pic: 1
  position: Yurt Müdürü
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: stack-overflow
      url: #

- name: Ahmet Faruk Arvas
  pic: 2
  position: Kıdemli Eğitim Danışmanı
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #

- name: Mustafa Bal
  pic: 3
  position: Müdür Yardımcısı
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: 
  - title: facebook
    url:
  - title: stack-overflow
    url: 
  - title: bitbucket 
    url: 
  - title: github
    url: 

# Postal address (add as many lines as necessary)
address:
  - line: Bahçelievler Mahallesi 
  - line: Karanfil Sokak. No:54
  - line: 14100 Bolu Merkez/Bolu

# Build settings
markdown: kramdown
permalink: pretty
